package com.onechekoutv1.dto;
// Generated Oct 2, 2012 3:11:56 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Currency generated by hbm2java
 */
//syamsul
@Entity
@Table(name="currency"
    ,schema="public"
)
public class Currency  implements java.io.Serializable {


     private String id;
     private String name;
     private String currencyCode;
     private String alpha3Code;

    public Currency() {
    }
	
    public Currency(String id, String name) {
        this.id = id;
        this.name = name;
    }
    public Currency(String id, String name, String currencyCode) {
       this.id = id;
       this.name = name;
       this.currencyCode = currencyCode;
    }
   
    @Id 
    @Column(name="id", unique=true, nullable=false, length=3)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="currency_code", length=3)
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * @return the alpha3Code
     */
    @Column(name="alpha3_code", length=3)
    public String getAlpha3Code() {
        return alpha3Code;
    }

    /**
     * @param alpha3Code the alpha3Code to set
     */
    public void setAlpha3Code(String alpha3Code) {
        this.alpha3Code = alpha3Code;
    }
    
}