package com.onechekoutv1.dto;
// Generated Oct 2, 2012 3:11:56 PM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MerchantPaymentChannel generated by hbm2java
 */
@Entity
@Table(name = "merchant_payment_channel", schema = "public")
public class MerchantPaymentChannel implements Serializable {

    private int merchantPaymentChannelId;
    private PaymentChannel paymentChannel;
    private Merchants merchants;
    private Boolean merchantPaymentChannelStatus;
    private String merchantPaymentChannelUid;
    private String merchantPaymentChannelPid;
    private String merchantPaymentChannelHash;
    private String merchantPaymentChannelPluginPrePayment;
    private String merchantPaymentChannelPluginPostPayment;
    private String merchantPaymentChannelPluginPreVoid;
    private String merchantPaymentChannelPluginPostVoid;
    private Integer invExpiredInMinutes;
    private Character merchantPaymentChannelMethodCipmip;
    private int paymentChannelCode;
    private Integer paymentChannelChainCode;
    private String VAInitNumber;
    private String VADefaultTraceNumber;
    private Set<Transactions> transactionses = new HashSet<Transactions>(0);
    private String VAInitNumberOpen;

    public MerchantPaymentChannel() {
    }

    public MerchantPaymentChannel(int merchantPaymentChannelId, PaymentChannel paymentChannel, Merchants merchants) {
        this.merchantPaymentChannelId = merchantPaymentChannelId;
        this.paymentChannel = paymentChannel;
        this.merchants = merchants;
    }

    public MerchantPaymentChannel(int merchantPaymentChannelId, PaymentChannel paymentChannel, Merchants merchants, Boolean merchantPaymentChannelStatus, String merchantPaymentChannelUid, String merchantPaymentChannelPid, String merchantPaymentChannelHash, String merchantPaymentChannelPluginPrePayment, String merchantPaymentChannelPluginPostPayment, String merchantPaymentChannelPluginPreVoid, String merchantPaymentChannelPluginPostVoid, Character merchantPaymentChannelMethodCipmip, Set<Transactions> transactionses) {
        this.merchantPaymentChannelId = merchantPaymentChannelId;
        this.paymentChannel = paymentChannel;
        this.merchants = merchants;
        this.merchantPaymentChannelStatus = merchantPaymentChannelStatus;
        this.merchantPaymentChannelUid = merchantPaymentChannelUid;
        this.merchantPaymentChannelPid = merchantPaymentChannelPid;
        this.merchantPaymentChannelHash = merchantPaymentChannelHash;
        this.merchantPaymentChannelPluginPrePayment = merchantPaymentChannelPluginPrePayment;
        this.merchantPaymentChannelPluginPostPayment = merchantPaymentChannelPluginPostPayment;
        this.merchantPaymentChannelPluginPreVoid = merchantPaymentChannelPluginPreVoid;
        this.merchantPaymentChannelPluginPostVoid = merchantPaymentChannelPluginPostVoid;
        this.merchantPaymentChannelMethodCipmip = merchantPaymentChannelMethodCipmip;
        this.transactionses = transactionses;
    }

    @Id
    @Column(name = "merchant_payment_channel_id", unique = true, nullable = false)
    public int getMerchantPaymentChannelId() {
        return this.merchantPaymentChannelId;
    }

    public void setMerchantPaymentChannelId(int merchantPaymentChannelId) {
        this.merchantPaymentChannelId = merchantPaymentChannelId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "payment_channel_id", nullable = false)
    public PaymentChannel getPaymentChannel() {
        return this.paymentChannel;
    }

    public void setPaymentChannel(PaymentChannel paymentChannel) {
        this.paymentChannel = paymentChannel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "merchant_idx", nullable = false)
    public Merchants getMerchants() {
        return this.merchants;
    }

    public void setMerchants(Merchants merchants) {
        this.merchants = merchants;
    }

    @Column(name = "merchant_payment_channel_status")
    public Boolean getMerchantPaymentChannelStatus() {
        return this.merchantPaymentChannelStatus;
    }

    public void setMerchantPaymentChannelStatus(Boolean merchantPaymentChannelStatus) {
        this.merchantPaymentChannelStatus = merchantPaymentChannelStatus;
    }

    @Column(name = "merchant_payment_channel_uid", length = 200)
    public String getMerchantPaymentChannelUid() {
        return this.merchantPaymentChannelUid;
    }

    public void setMerchantPaymentChannelUid(String merchantPaymentChannelUid) {
        this.merchantPaymentChannelUid = merchantPaymentChannelUid;
    }

    @Column(name = "merchant_payment_channel_pid", length = 200)
    public String getMerchantPaymentChannelPid() {
        return this.merchantPaymentChannelPid;
    }

    public void setMerchantPaymentChannelPid(String merchantPaymentChannelPid) {
        this.merchantPaymentChannelPid = merchantPaymentChannelPid;
    }

    @Column(name = "merchant_payment_channel_hash", length = 100)
    public String getMerchantPaymentChannelHash() {
        return this.merchantPaymentChannelHash;
    }

    public void setMerchantPaymentChannelHash(String merchantPaymentChannelHash) {
        this.merchantPaymentChannelHash = merchantPaymentChannelHash;
    }

    @Column(name = "merchant_payment_channel_plugin_pre_payment", length = 1024)
    public String getMerchantPaymentChannelPluginPrePayment() {
        return this.merchantPaymentChannelPluginPrePayment;
    }

    public void setMerchantPaymentChannelPluginPrePayment(String merchantPaymentChannelPluginPrePayment) {
        this.merchantPaymentChannelPluginPrePayment = merchantPaymentChannelPluginPrePayment;
    }

    @Column(name = "merchant_payment_channel_plugin_post_payment", length = 1024)
    public String getMerchantPaymentChannelPluginPostPayment() {
        return this.merchantPaymentChannelPluginPostPayment;
    }

    public void setMerchantPaymentChannelPluginPostPayment(String merchantPaymentChannelPluginPostPayment) {
        this.merchantPaymentChannelPluginPostPayment = merchantPaymentChannelPluginPostPayment;
    }

    @Column(name = "merchant_payment_channel_plugin_pre_void", length = 1024)
    public String getMerchantPaymentChannelPluginPreVoid() {
        return this.merchantPaymentChannelPluginPreVoid;
    }

    public void setMerchantPaymentChannelPluginPreVoid(String merchantPaymentChannelPluginPreVoid) {
        this.merchantPaymentChannelPluginPreVoid = merchantPaymentChannelPluginPreVoid;
    }

    @Column(name = "merchant_payment_channel_plugin_post_void", length = 1024)
    public String getMerchantPaymentChannelPluginPostVoid() {
        return this.merchantPaymentChannelPluginPostVoid;
    }

    public void setMerchantPaymentChannelPluginPostVoid(String merchantPaymentChannelPluginPostVoid) {
        this.merchantPaymentChannelPluginPostVoid = merchantPaymentChannelPluginPostVoid;
    }

    @Column(name = "merchant_payment_channel_method_cipmip", length = 1)
    public Character getMerchantPaymentChannelMethodCipmip() {
        return this.merchantPaymentChannelMethodCipmip;
    }

    public void setMerchantPaymentChannelMethodCipmip(Character merchantPaymentChannelMethodCipmip) {
        this.merchantPaymentChannelMethodCipmip = merchantPaymentChannelMethodCipmip;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "merchantPaymentChannel")
    public Set<Transactions> getTransactionses() {
        return this.transactionses;
    }

    public void setTransactionses(Set<Transactions> transactionses) {
        this.transactionses = transactionses;
    }

    /**
     * @return the paymentChannelCode
     */
    @Column(name = "payment_channel_code", nullable = false)
    public int getPaymentChannelCode() {
        return paymentChannelCode;
    }

    /**
     * @param paymentChannelCode the paymentChannelCode to set
     */
    public void setPaymentChannelCode(int paymentChannelCode) {
        this.paymentChannelCode = paymentChannelCode;
    }

    /**
     * @return the VAInitNumber
     */
    @Column(name = "va_init_number")
    public String getVAInitNumber() {
        return VAInitNumber;
    }

    /**
     * @param VAInitNumber the VAInitNumber to set
     */
    public void setVAInitNumber(String VAInitNumber) {
        this.VAInitNumber = VAInitNumber;
    }

    /**
     * @return the VADefaultTraceNumber
     */
    @Column(name = "va_default_trace_number")
    public String getVADefaultTraceNumber() {
        return VADefaultTraceNumber;
    }

    /**
     * @param VADefaultTraceNumber the VADefaultTraceNumber to set
     */
    public void setVADefaultTraceNumber(String VADefaultTraceNumber) {
        this.VADefaultTraceNumber = VADefaultTraceNumber;
    }

    @Column(name = "inv_expired_in_minutes")
    public Integer getInvExpiredInMinutes() {
        return this.invExpiredInMinutes;
    }

    public void setInvExpiredInMinutes(Integer invExpiredInMinutes) {
        this.invExpiredInMinutes = invExpiredInMinutes;
    }

    /**
     * @return the paymentChannelChainCode
     */
    @Column(name = "payment_channel_chain_code")
    public Integer getPaymentChannelChainCode() {
        return paymentChannelChainCode;
    }

    /**
     * @param paymentChannelChainCode the paymentChannelChainCode to set
     */
    public void setPaymentChannelChainCode(Integer paymentChannelChainCode) {
        this.paymentChannelChainCode = paymentChannelChainCode;
    }

    @Column(name = "va_init_number_open")
    public String getVAInitNumberOpen() {
        return VAInitNumberOpen;
    }

    public void setVAInitNumberOpen(String VAInitNumberOpen) {
        this.VAInitNumberOpen = VAInitNumberOpen;
    }

}
