package com.onechekoutv1.dto;
// Generated Oct 2, 2012 3:11:56 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Merchants generated by hbm2java
 */
@Entity
@Table(name = "merchants", schema = "public", uniqueConstraints
        = @UniqueConstraint(columnNames = {"merchant_code", "merchant_chain_merchant_code"}))
public class Merchants implements java.io.Serializable {

    private String merchantPaycodeEmailSubject;
    private String merchantPaycodeEmailCc;
    private int merchantIdx;
    private int merchantCode;
    private Integer merchantChainMerchantCode;
    private Date merchantRegDate;
    private Boolean merchantStatus;
    private Boolean merchantReusablePaycode;
    private Boolean merchantDirectInquiry;
    private String merchantAddress;
    private String merchantHashPassword;
    private String merchantShaFormat;
    private String merchantCompanyName;
    private String merchantName;
    private String merchantPluginPrePayment;
    private String merchantPluginPostPayment;
    private String merchantPluginPreVoid;
    private String merchantPluginPostVoid;
    private String merchantNotifyStatusUrl;
    private String merchantAdditionalUrl;
    private String merchantRedirectUrl;
    private String merchantReconcileUrl;
    private String merchantIdentifyUrl;
    private String merchantReviewUrl;
    private String traceNumber;
    private Character merchantCategory;
    private String merchantCybersourceReviewUrl;
    private Integer merchantConnectionTimeout;
    private Integer merchantReadTimeout;
    private Integer invExpiredInMinutes;
    private String merchantProcessor;
    private Boolean merchantRetry;
    private Boolean merchantNotifyTimeout;
    private Boolean merchantEscrow;
    private String merchantEmail;
    private String merchantPluginPostParsePayment;
    private String merchantFxrateFeature;
    private Integer merchantRetryNotifyNumber;
    private Set<MerchantPaymentChannel> merchantPaymentChannels = new HashSet<MerchantPaymentChannel>(0);

    public Merchants() {
    }

    public Merchants(int merchantIdx, int merchantCode) {
        this.merchantIdx = merchantIdx;
        this.merchantCode = merchantCode;
    }

    public Merchants(int merchantIdx, int merchantCode, Integer merchantChainMerchantCode, Date merchantRegDate, Boolean merchantStatus, String merchantAddress, String merchantHashPassword, String merchantShaFormat, String merchantCompanyName, String merchantName, String merchantPluginPrePayment, String merchantPluginPostPayment, String merchantPluginPreVoid, String merchantPluginPostVoid, String merchantNotifyStatusUrl, String merchantAdditionalUrl, String merchantRedirectUrl, Character merchantCategory, String merchantCybersourceReviewUrl, Integer merchantConnectionTimeout, Integer merchantReadTimeout, Integer invExpiredInMinutes, Set<MerchantPaymentChannel> merchantPaymentChannels) {
        this.merchantIdx = merchantIdx;
        this.merchantCode = merchantCode;
        this.merchantChainMerchantCode = merchantChainMerchantCode;
        this.merchantRegDate = merchantRegDate;
        this.merchantStatus = merchantStatus;
        this.merchantAddress = merchantAddress;
        this.merchantHashPassword = merchantHashPassword;
        this.merchantShaFormat = merchantShaFormat;
        this.merchantCompanyName = merchantCompanyName;
        this.merchantName = merchantName;
        this.merchantPluginPrePayment = merchantPluginPrePayment;
        this.merchantPluginPostPayment = merchantPluginPostPayment;
        this.merchantPluginPreVoid = merchantPluginPreVoid;
        this.merchantPluginPostVoid = merchantPluginPostVoid;
        this.merchantNotifyStatusUrl = merchantNotifyStatusUrl;
        this.merchantAdditionalUrl = merchantAdditionalUrl;
        this.merchantRedirectUrl = merchantRedirectUrl;
        this.merchantCategory = merchantCategory;
        this.merchantCybersourceReviewUrl = merchantCybersourceReviewUrl;
        this.merchantConnectionTimeout = merchantConnectionTimeout;
        this.merchantReadTimeout = merchantReadTimeout;
        this.invExpiredInMinutes = invExpiredInMinutes;
        this.merchantPaymentChannels = merchantPaymentChannels;
    }

    @Id
    @Column(name = "merchant_idx", unique = true, nullable = false)
    public int getMerchantIdx() {
        return this.merchantIdx;
    }

    public void setMerchantIdx(int merchantIdx) {
        this.merchantIdx = merchantIdx;
    }

    @Column(name = "merchant_code", nullable = false)
    public int getMerchantCode() {
        return this.merchantCode;
    }

    public void setMerchantCode(int merchantCode) {
        this.merchantCode = merchantCode;
    }

    @Column(name = "merchant_chain_merchant_code")
    public Integer getMerchantChainMerchantCode() {
        return this.merchantChainMerchantCode;
    }

    public void setMerchantChainMerchantCode(Integer merchantChainMerchantCode) {
        this.merchantChainMerchantCode = merchantChainMerchantCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "merchant_reg_date", length = 35)
    public Date getMerchantRegDate() {
        return this.merchantRegDate;
    }

    public void setMerchantRegDate(Date merchantRegDate) {
        this.merchantRegDate = merchantRegDate;
    }

    @Column(name = "merchant_status")
    public Boolean getMerchantStatus() {
        return this.merchantStatus;
    }

    public void setMerchantStatus(Boolean merchantStatus) {
        this.merchantStatus = merchantStatus;
    }

    @Column(name = "merchant_retry")
    public Boolean getMerchantRetry() {
        return this.merchantRetry;
    }

    public void setMerchantRetry(Boolean merchantRetry) {
        this.merchantRetry = merchantRetry;
    }

    @Column(name = "merchant_address", length = 128)
    public String getMerchantAddress() {
        return this.merchantAddress;
    }

    public void setMerchantAddress(String merchantAddress) {
        this.merchantAddress = merchantAddress;
    }

    @Column(name = "merchant_hash_password", length = 250)
    public String getMerchantHashPassword() {
        return this.merchantHashPassword;
    }

    public void setMerchantHashPassword(String merchantHashPassword) {
        this.merchantHashPassword = merchantHashPassword;
    }

    @Column(name = "merchant_sha_format", length = 10)
    public String getMerchantShaFormat() {
        return this.merchantShaFormat;
    }

    public void setMerchantShaFormat(String merchantShaFormat) {
        this.merchantShaFormat = merchantShaFormat;
    }

    @Column(name = "merchant_company_name", length = 100)
    public String getMerchantCompanyName() {
        return this.merchantCompanyName;
    }

    public void setMerchantCompanyName(String merchantCompanyName) {
        this.merchantCompanyName = merchantCompanyName;
    }

    @Column(name = "merchant_name", length = 100)
    public String getMerchantName() {
        return this.merchantName;
    }

    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    @Column(name = "merchant_plugin_pre_payment", length = 1024)
    public String getMerchantPluginPrePayment() {
        return this.merchantPluginPrePayment;
    }

    public void setMerchantPluginPrePayment(String merchantPluginPrePayment) {
        this.merchantPluginPrePayment = merchantPluginPrePayment;
    }

    @Column(name = "merchant_plugin_post_payment", length = 1024)
    public String getMerchantPluginPostPayment() {
        return this.merchantPluginPostPayment;
    }

    public void setMerchantPluginPostPayment(String merchantPluginPostPayment) {
        this.merchantPluginPostPayment = merchantPluginPostPayment;
    }

    @Column(name = "merchant_plugin_pre_void", length = 1024)
    public String getMerchantPluginPreVoid() {
        return this.merchantPluginPreVoid;
    }

    public void setMerchantPluginPreVoid(String merchantPluginPreVoid) {
        this.merchantPluginPreVoid = merchantPluginPreVoid;
    }

    @Column(name = "merchant_plugin_post_void", length = 1024)
    public String getMerchantPluginPostVoid() {
        return this.merchantPluginPostVoid;
    }

    public void setMerchantPluginPostVoid(String merchantPluginPostVoid) {
        this.merchantPluginPostVoid = merchantPluginPostVoid;
    }

    @Column(name = "merchant_notify_status_url", length = 200)
    public String getMerchantNotifyStatusUrl() {
        return this.merchantNotifyStatusUrl;
    }

    public void setMerchantNotifyStatusUrl(String merchantNotifyStatusUrl) {
        this.merchantNotifyStatusUrl = merchantNotifyStatusUrl;
    }

    @Column(name = "merchant_additional_url", length = 200)
    public String getMerchantAdditionalUrl() {
        return this.merchantAdditionalUrl;
    }

    public void setMerchantAdditionalUrl(String merchantAdditionalUrl) {
        this.merchantAdditionalUrl = merchantAdditionalUrl;
    }

    @Column(name = "merchant_redirect_url", length = 200)
    public String getMerchantRedirectUrl() {
        return this.merchantRedirectUrl;
    }

    public void setMerchantRedirectUrl(String merchantRedirectUrl) {
        this.merchantRedirectUrl = merchantRedirectUrl;
    }

    @Column(name = "merchant_category", length = 1)
    public Character getMerchantCategory() {
        return this.merchantCategory;
    }

    public void setMerchantCategory(Character merchantCategory) {
        this.merchantCategory = merchantCategory;
    }

    @Column(name = "merchant_cybersource_review_url", length = 200)
    public String getMerchantCybersourceReviewUrl() {
        return this.merchantCybersourceReviewUrl;
    }

    public void setMerchantCybersourceReviewUrl(String merchantCybersourceReviewUrl) {
        this.merchantCybersourceReviewUrl = merchantCybersourceReviewUrl;
    }

    @Column(name = "merchant_connection_timeout")
    public Integer getMerchantConnectionTimeout() {
        return this.merchantConnectionTimeout;
    }

    public void setMerchantConnectionTimeout(Integer merchantConnectionTimeout) {
        this.merchantConnectionTimeout = merchantConnectionTimeout;
    }

    @Column(name = "merchant_read_timeout")
    public Integer getMerchantReadTimeout() {
        return this.merchantReadTimeout;
    }

    public void setMerchantReadTimeout(Integer merchantReadTimeout) {
        this.merchantReadTimeout = merchantReadTimeout;
    }

    @Column(name = "inv_expired_in_minutes")
    public Integer getInvExpiredInMinutes() {
        return this.invExpiredInMinutes;
    }

    public void setInvExpiredInMinutes(Integer invExpiredInMinutes) {
        this.invExpiredInMinutes = invExpiredInMinutes;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "merchants")
    public Set<MerchantPaymentChannel> getMerchantPaymentChannels() {
        return this.merchantPaymentChannels;
    }

    public void setMerchantPaymentChannels(Set<MerchantPaymentChannel> merchantPaymentChannels) {
        this.merchantPaymentChannels = merchantPaymentChannels;
    }

    /**
     * @return the traceNumber
     */
    @Column(name = "trace_number")
    public String getTraceNumber() {
        return traceNumber;
    }

    /**
     * @param traceNumber the traceNumber to set
     */
    public void setTraceNumber(String traceNumber) {
        this.traceNumber = traceNumber;
    }

    /**
     * @return the merchantReconcileUrl
     */
    @Column(name = "merchant_reconcile_url", length = 200)
    public String getMerchantReconcileUrl() {
        return merchantReconcileUrl;
    }

    /**
     * @param merchantReconcileUrl the merchantReconcileUrl to set
     */
    public void setMerchantReconcileUrl(String merchantReconcileUrl) {
        this.merchantReconcileUrl = merchantReconcileUrl;
    }

    /**
     * @return the merchantIdentifyUrl
     */
    @Column(name = "merchant_identify_url", length = 200)
    public String getMerchantIdentifyUrl() {
        return merchantIdentifyUrl;
    }

    /**
     * @param merchantIdentifyUrl the merchantIdentifyUrl to set
     */
    public void setMerchantIdentifyUrl(String merchantIdentifyUrl) {
        this.merchantIdentifyUrl = merchantIdentifyUrl;
    }

    /**
     * @return the merchantProcessor
     */
    @Column(name = "merchant_processor", length = 1024)
    public String getMerchantProcessor() {
        return merchantProcessor;
    }

    /**
     * @param merchantProcessor the merchantProcessor to set
     */
    public void setMerchantProcessor(String merchantProcessor) {
        this.merchantProcessor = merchantProcessor;
    }

    /**
     * @return the merchantReviewUrl
     */
    @Column(name = "merchant_review_url", length = 200)
    public String getMerchantReviewUrl() {
        return merchantReviewUrl;
    }

    /**
     * @param merchantReviewUrl the merchantReviewUrl to set
     */
    public void setMerchantReviewUrl(String merchantReviewUrl) {
        this.merchantReviewUrl = merchantReviewUrl;
    }

    /**
     * @return the merchantReusablePaycode
     */
    @Column(name = "merchant_reusable_paycode")
    public Boolean getMerchantReusablePaycode() {
        return merchantReusablePaycode;
    }

    /**
     * @param merchantReusablePaycode the merchantReusablePaycode to set
     */
    public void setMerchantReusablePaycode(Boolean merchantReusablePaycode) {
        this.merchantReusablePaycode = merchantReusablePaycode;
    }

    /**
     * @return the merchantDirectInquiry
     */
    @Column(name = "merchant_direct_inquiry")
    public Boolean getMerchantDirectInquiry() {
        return merchantDirectInquiry;
    }

    /**
     * @param merchantReusablePaycode the merchantDirectInquiry to set
     */
    public void setMerchantDirectInquiry(Boolean merchantDirectInquiry) {
        this.merchantDirectInquiry = merchantDirectInquiry;
    }

    /**
     * @return the merchantNotifyTimeout
     */
    @Column(name = "merchant_notify_timeout")
    public Boolean getMerchantNotifyTimeout() {
        return merchantNotifyTimeout;
    }

    /**
     * @param merchantNotifyTimeout the merchantNotifyTimeout to set
     */
    public void setMerchantNotifyTimeout(Boolean merchantNotifyTimeout) {
        this.merchantNotifyTimeout = merchantNotifyTimeout;
    }

    @Column(name = "merchant_escrow")
    public Boolean getMerchantEscrow() {
        return merchantEscrow;
    }

    public void setMerchantEscrow(Boolean merchantEscrow) {
        this.merchantEscrow = merchantEscrow;
    }

    /**
     * @return the merchantProcessor
     */
    @Column(name = "merchant_email", length = 200)
    public String getMerchantEmail() {
        return merchantEmail;
    }

    /**
     * @param merchantProcessor the merchantProcessor to set
     */
    public void setMerchantEmail(String merchantEmail) {
        this.merchantEmail = merchantEmail;
    }

    @Column(name = "merchant_plugin_post_parse_payment", length = 1024)
    public String getMerchantPluginPostParsePayment() {
        return merchantPluginPostParsePayment;
    }

    public void setMerchantPluginPostParsePayment(String merchantPluginPostParsePayment) {
        this.merchantPluginPostParsePayment = merchantPluginPostParsePayment;
    }

    /**
     * @return the merchantProcessor
     */
    @Column(name = "merchant_fxrate_feature", length = 4)
    public String getMerchantFxrateFeature() {
        return merchantFxrateFeature;
    }

    /**
     * @param merchantProcessor the merchantProcessor to set
     */
    public void setMerchantFxrateFeature(String merchantFxrateFeature) {
        this.merchantFxrateFeature = merchantFxrateFeature;
    }

    @Column(name = "merchant_retry_notify_number")
    public Integer getMerchantRetryNotifyNumber() {
        return this.merchantRetryNotifyNumber;
    }

    public void setMerchantRetryNotifyNumber(Integer merchantRetryNotifyNumber) {
        this.merchantRetryNotifyNumber = merchantRetryNotifyNumber;
    }
//
//    @Column(name="merchant_escrow")
//    public Boolean getMerchantEscrow() {
//        return this.merchantEscrow;
//    }
//
//    public void setMerchantEscrow(Boolean merchantEscrow) {
//        this.merchantEscrow = merchantEscrow;
//    }

    @Column(name = "merchant_paycode_email_subject")
    public String getMerchantPaycodeEmailSubject() {
        return merchantPaycodeEmailSubject;
    }

    public void setMerchantPaycodeEmailSubject(String merchantPaycodeEmailSubject) {
        this.merchantPaycodeEmailSubject = merchantPaycodeEmailSubject;
    }

    @Column(name = "merchant_paycode_email_cc")
    public String getMerchantPaycodeEmailCc() {
        return merchantPaycodeEmailCc;
    }

    public void setMerchantPaycodeEmailCc(String merchantPaycodeEmailCc) {
        this.merchantPaycodeEmailCc = merchantPaycodeEmailCc;
    }

}
