package com.onechekoutv1.dto;
// Generated Oct 2, 2012 3:11:56 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentChannel generated by hbm2java
 */
@Entity
@Table(name="payment_channel"
    ,schema="public"
)
public class PaymentChannel  implements java.io.Serializable {


     private String paymentChannelId;
     private String paymentChannelName;
     private String paymentChannelProcessor;
     private Boolean paymentChannelStatus;
     private String redirectPaymentUrlMip;
     private String voidUrl;
     private String redirectPaymentUrlCip;
     private String redirectPaymentUrlMipXml;
     private String checkStatusUrl;
     private String serviceId;
     private String reversalPaymentUrl;
     private Integer paymentChannelConnectionTimeout;
     private Integer paymentChannelReadTimeout;       
     
     private Set<MerchantPaymentChannel> merchantPaymentChannels = new HashSet<MerchantPaymentChannel>(0);

    public PaymentChannel() {
    }
	
    public PaymentChannel(String paymentChannelId) {
        this.paymentChannelId = paymentChannelId;
    }
    public PaymentChannel(String paymentChannelId, String paymentChannelName, String paymentChannelProcessor, Boolean paymentChannelStatus, String redirectPaymentUrlMip, String voidUrl, String redirectPaymentUrlCip, Set<MerchantPaymentChannel> merchantPaymentChannels) {
       this.paymentChannelId = paymentChannelId;
       this.paymentChannelName = paymentChannelName;
       this.paymentChannelProcessor = paymentChannelProcessor;
       this.paymentChannelStatus = paymentChannelStatus;
       this.redirectPaymentUrlMip = redirectPaymentUrlMip;
       this.voidUrl = voidUrl;
       this.redirectPaymentUrlCip = redirectPaymentUrlCip;
       this.merchantPaymentChannels = merchantPaymentChannels;
    }
   
    @Id
    @Column(name="payment_channel_id", unique=true, nullable=false, length=2)
    public String getPaymentChannelId() {
        return this.paymentChannelId;
    }
    
    public void setPaymentChannelId(String paymentChannelId) {
        this.paymentChannelId = paymentChannelId;
    }
    
    @Column(name="payment_channel_name", length=100)
    public String getPaymentChannelName() {
        return this.paymentChannelName;
    }
    
    public void setPaymentChannelName(String paymentChannelName) {
        this.paymentChannelName = paymentChannelName;
    }
    
    @Column(name="payment_channel_processor", length=300)
    public String getPaymentChannelProcessor() {
        return this.paymentChannelProcessor;
    }
    
    public void setPaymentChannelProcessor(String paymentChannelProcessor) {
        this.paymentChannelProcessor = paymentChannelProcessor;
    }
    
    @Column(name="payment_channel_status")
    public Boolean getPaymentChannelStatus() {
        return this.paymentChannelStatus;
    }
    
    public void setPaymentChannelStatus(Boolean paymentChannelStatus) {
        this.paymentChannelStatus = paymentChannelStatus;
    }
    
    @Column(name="redirect_payment_url_mip", length=200)
    public String getRedirectPaymentUrlMip() {
        return this.redirectPaymentUrlMip;
    }
    
    public void setRedirectPaymentUrlMip(String redirectPaymentUrlMip) {
        this.redirectPaymentUrlMip = redirectPaymentUrlMip;
    }
    
    @Column(name="void_url", length=200)
    public String getVoidUrl() {
        return this.voidUrl;
    }
    
    public void setVoidUrl(String voidUrl) {
        this.voidUrl = voidUrl;
    }
    
    @Column(name="redirect_payment_url_cip", length=200)
    public String getRedirectPaymentUrlCip() {
        return this.redirectPaymentUrlCip;
    }
    
    public void setRedirectPaymentUrlCip(String redirectPaymentUrlCip) {
        this.redirectPaymentUrlCip = redirectPaymentUrlCip;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="paymentChannel")
    public Set<MerchantPaymentChannel> getMerchantPaymentChannels() {
        return this.merchantPaymentChannels;
    }
    
    public void setMerchantPaymentChannels(Set<MerchantPaymentChannel> merchantPaymentChannels) {
        this.merchantPaymentChannels = merchantPaymentChannels;
    }

    /**
     * @return the redirectPaymentUrlMipXml
     */
    @Column(name="redirect_payment_url_mip_xml", length=200)
    public String getRedirectPaymentUrlMipXml() {
        return redirectPaymentUrlMipXml;
    }

    /**
     * @param redirectPaymentUrlMipXml the redirectPaymentUrlMipXml to set
     */
    public void setRedirectPaymentUrlMipXml(String redirectPaymentUrlMipXml) {
        this.redirectPaymentUrlMipXml = redirectPaymentUrlMipXml;
    }

    /**
     * @return the serviceId
     */
    @Column(name="service_id", length=10)
    public String getServiceId() {
        return serviceId;
    }

    /**
     * @param serviceId the serviceId to set
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    @Column(name="check_status_url", length=200)
    public String getCheckStatusUrl() {
        return checkStatusUrl;
    }

    public void setCheckStatusUrl(String checkStatusUrl) {
        this.checkStatusUrl = checkStatusUrl;
    }

    @Column(name="reversal_payment_url", length=200)
    public String getReversalPaymentUrl() {
        return reversalPaymentUrl;
    }

    public void setReversalPaymentUrl(String reversalPaymentUrl) {
        this.reversalPaymentUrl = reversalPaymentUrl;
    }
    
   @Column(name="payment_channel_connection_timeout")
    public Integer getPaymentChannelConnectionTimeout() {
        return this.paymentChannelConnectionTimeout;
    }
    
    public void setPaymentChannelConnectionTimeout(Integer paymentChannelConnectionTimeout) {
        this.paymentChannelConnectionTimeout = paymentChannelConnectionTimeout;
    }
    
    @Column(name="payment_channel_read_timeout")
    public Integer getPaymentChannelReadTimeout() {
        return this.paymentChannelReadTimeout;
    }
    
    public void setPaymentChannelReadTimeout(Integer paymentChannelReadTimeout) {
        this.paymentChannelReadTimeout = paymentChannelReadTimeout;
    }        
    
}