package com.onechekoutv1.dto;
// Generated Oct 2, 2012 3:11:56 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SeqTransactionIdNextval generated by hbm2java
 */
@Entity
@Table(name="seq_transaction_id_nextval"
    ,schema="public"
)
public class SeqTransactionIdNextval  implements java.io.Serializable {


     private Integer nextval;

    public SeqTransactionIdNextval() {
    }

    public SeqTransactionIdNextval(Integer nextval) {
       this.nextval = nextval;
    }
   
     @Id 
    
    @Column(name="nextval")
    public Integer getNextval() {
        return this.nextval;
    }
    
    public void setNextval(Integer nextval) {
        this.nextval = nextval;
    }

}

