package com.onechekoutv1.dto;
// Generated Oct 2, 2012 3:11:56 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TransactionsDataNonAirlines generated by hbm2java
 */
@Entity
@Table(name="transactions_data_non_airlines"
    ,schema="public"
)
public class TransactionsDataNonAirlines  implements java.io.Serializable {

     private long transactionsId;
     private Transactions transactions;
     private String incBasket;
     private String incShippingAddress;
     private String incShippingCity;
     private String incShippingState;
     private String incShippingCountry;
     private String incShippingZipcode;

    public TransactionsDataNonAirlines() {
    }

	
    public TransactionsDataNonAirlines(long transactionsId, Transactions transactions, String incBasket) {
        this.transactionsId = transactionsId;
        this.transactions = transactions;
        this.incBasket = incBasket;
    }
    public TransactionsDataNonAirlines(long transactionsId, Transactions transactions, String incBasket, String incShippingAddress, String incShippingCity, String incShippingState, String incShippingCountry, String incShippingZipcode) {
       this.transactionsId = transactionsId;
       this.transactions = transactions;
       this.incBasket = incBasket;
       this.incShippingAddress = incShippingAddress;
       this.incShippingCity = incShippingCity;
       this.incShippingState = incShippingState;
       this.incShippingCountry = incShippingCountry;
       this.incShippingZipcode = incShippingZipcode;
    }
   
    @Id 
    @Column(name="id", unique=true, nullable=false)
    public long getTransactionsId() {
        return this.transactionsId;
    }
    
    public void setTransactionsId(long transactionsId) {
        this.transactionsId = transactionsId;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="transactions_id", unique=true, nullable=false)
    public Transactions getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Transactions transactions) {
        this.transactions = transactions;
    }
    
    @Column(name="inc_basket", nullable=false, length=1024)
    public String getIncBasket() {
        return this.incBasket;
    }
    
    public void setIncBasket(String incBasket) {
        this.incBasket = incBasket;
    }
    
    @Column(name="inc_shipping_address", length=1024)
    public String getIncShippingAddress() {
        return this.incShippingAddress;
    }
    
    public void setIncShippingAddress(String incShippingAddress) {
        this.incShippingAddress = incShippingAddress;
    }
    
    @Column(name="inc_shipping_city", length=100)
    public String getIncShippingCity() {
        return this.incShippingCity;
    }
    
    public void setIncShippingCity(String incShippingCity) {
        this.incShippingCity = incShippingCity;
    }
    
    @Column(name="inc_shipping_state", length=100)
    public String getIncShippingState() {
        return this.incShippingState;
    }
    
    public void setIncShippingState(String incShippingState) {
        this.incShippingState = incShippingState;
    }
    
    @Column(name="inc_shipping_country", length=3)
    public String getIncShippingCountry() {
        return this.incShippingCountry;
    }
    
    public void setIncShippingCountry(String incShippingCountry) {
        this.incShippingCountry = incShippingCountry;
    }
    
    @Column(name="inc_shipping_zipcode", length=10)
    public String getIncShippingZipcode() {
        return this.incShippingZipcode;
    }
    
    public void setIncShippingZipcode(String incShippingZipcode) {
        this.incShippingZipcode = incShippingZipcode;
    }
    
}