package com.onechekoutv1.dto;
// Generated Oct 2, 2012 3:11:56 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name = "transactions", schema = "public")
public class Transactions implements java.io.Serializable {

    private long transactionsId;
    private MerchantPaymentChannel merchantPaymentChannel;
    private Rates rates;
    private int incMallid;
    private Integer incChainmerchant;
    private BigDecimal incAmount;
    private BigDecimal incPurchaseamount;
    private String incTransidmerchant;
    private String incWords;
    private Date incRequestdatetime;
    private String incCurrency;
    private Long parentTransactions;
    private Character transactionsType;
    private String incPurchasecurrency;
    private String incSessionid;
    private String incEmail;
    private String incPaymentchannel;
    private String incInstallmentAcquirer;
    private String incTenor;
    private String incPromoid;
    private String incAdditionalInformation;
    private String accountId;
    private String systemSession;
    private Character transactionsStatus;
    private Character transactionsState;
    private Date transactionsDatetime;
    private Date reconcileDateTime;
    private Date dokuInquiryInvoiceDatetime;
    private Date dokuInvokeStatusDatetime;
    private String dokuResponseCode;
    private String dokuApprovalCode;
    private String dokuHostRefNum;
    private String dokuResultMessage;
    private String dokuIssuerBank;
    private String dokuResult;
    private Date eduGetdataDatetime;
    private Date eduPassVoidDatetime;
    private Character eduStatus;
    private String eduReason;
    private Date redirectDatetime;
    private String systemMessage;
    private Integer verifyScore;
    private Character verifyStatus;
    private String verifyId;
    private Date verifyDatetime;
    private String dokuVoidResponseCode;
    private String dokuVoidApprovalCode;
    private Date dokuVoidDatetime;
    private String incName;
    private String inc3dSecureStatus;
    private String incLiability;
    private BigDecimal convertedAmount;
    private Set<TransactionsDataCardholder> transactionsDataCardholders = new HashSet<TransactionsDataCardholder>(0);
    private Set<TransactionsDataNonAirlines> transactionsDataNonAirlineses = new HashSet<TransactionsDataNonAirlines>(0);
    private Set<TransactionsDataAirlines> transactionsDataAirlineses = new HashSet<TransactionsDataAirlines>(0);
    private TransactionsDataRecur transactionsDataRecur;// = new HashSet<TransactionsDataRecur>(0);
//     private String recurSchedule;
    private String incCustomerId;
    //TOKENIZATION
    private String tokenId;
    //RED DEVICEID
    private String deviceId;

    private String merchantNotificationResponse;

    private Integer incRewards;
    private String trxCodeCore;
    private String ocoId;
    private Boolean PartialAmount = false;
    private Boolean OpenAmount = false;
//    private Integer batchId;
    //RED DEVICEID
    // private String deviceId;

    public Transactions() {
    }

    public Transactions(long transactionsId, MerchantPaymentChannel merchantPaymentChannel, Rates rates, int incMallid, BigDecimal incAmount, BigDecimal incPurchaseamount, String incTransidmerchant, String incWords, Date incRequestdatetime, String incCurrency, String incPurchasecurrency, String incSessionid, String incEmail, String incPaymentchannel, String accountId, String incName) {
        this.transactionsId = transactionsId;
        this.merchantPaymentChannel = merchantPaymentChannel;
        this.rates = rates;
        this.incMallid = incMallid;
        this.incAmount = incAmount;
        this.incPurchaseamount = incPurchaseamount;
        this.incTransidmerchant = incTransidmerchant;
        this.incWords = incWords;
        this.incRequestdatetime = incRequestdatetime;
        this.incCurrency = incCurrency;
        this.incPurchasecurrency = incPurchasecurrency;
        this.incSessionid = incSessionid;
        this.incEmail = incEmail;
        this.incPaymentchannel = incPaymentchannel;
        this.accountId = accountId;
        this.incName = incName;
    }

    public Transactions(long transactionsId, MerchantPaymentChannel merchantPaymentChannel, Rates rates, int incMallid, Integer incChainmerchant, BigDecimal incAmount, BigDecimal incPurchaseamount, String incTransidmerchant, String incWords, Date incRequestdatetime, String incCurrency, String incPurchasecurrency, String incSessionid, String incEmail, String incPaymentchannel, String incInstallmentAcquirer, String incTenor, String incPromoid, String incAdditionalInformation, String accountId, String systemSession, Character transactionsStatus, Character transactionsState, Date transactionsDatetime, Date dokuInquiryInvoiceDatetime, Date dokuInvokeStatusDatetime, String dokuResponseCode, String dokuApprovalCode, String dokuResultMessage, String dokuIssuerBank, String dokuResult, Date eduGetdataDatetime, Date eduPassVoidDatetime, Character eduStatus, String eduReason, Date redirectDatetime, String systemMessage, Integer verifyScore, Character verifyStatus, String verifyId, Date verifyDatetime, String dokuVoidResponseCode, String dokuVoidApprovalCode, Date dokuVoidDatetime, String incName, Set<TransactionsDataCardholder> transactionsDataCardholders, Set<TransactionsDataNonAirlines> transactionsDataNonAirlineses, Set<TransactionsDataAirlines> transactionsDataAirlineses, TransactionsDataRecur transactionsDataRecur) {
        this.transactionsId = transactionsId;
        this.merchantPaymentChannel = merchantPaymentChannel;
        this.rates = rates;
        this.incMallid = incMallid;
        this.incChainmerchant = incChainmerchant;
        this.incAmount = incAmount;
        this.incPurchaseamount = incPurchaseamount;
        this.incTransidmerchant = incTransidmerchant;
        this.incWords = incWords;
        this.incRequestdatetime = incRequestdatetime;
        this.incCurrency = incCurrency;
        this.incPurchasecurrency = incPurchasecurrency;
        this.incSessionid = incSessionid;
        this.incEmail = incEmail;
        this.incPaymentchannel = incPaymentchannel;
        this.incInstallmentAcquirer = incInstallmentAcquirer;
        this.incTenor = incTenor;
        this.incPromoid = incPromoid;
        this.incAdditionalInformation = incAdditionalInformation;
        this.accountId = accountId;
        this.systemSession = systemSession;
        this.transactionsStatus = transactionsStatus;
        this.transactionsState = transactionsState;
        this.transactionsDatetime = transactionsDatetime;
        this.dokuInquiryInvoiceDatetime = dokuInquiryInvoiceDatetime;
        this.dokuInvokeStatusDatetime = dokuInvokeStatusDatetime;
        this.dokuResponseCode = dokuResponseCode;
        this.dokuApprovalCode = dokuApprovalCode;
        this.dokuResultMessage = dokuResultMessage;
        this.dokuIssuerBank = dokuIssuerBank;
        this.dokuResult = dokuResult;
        this.eduGetdataDatetime = eduGetdataDatetime;
        this.eduPassVoidDatetime = eduPassVoidDatetime;
        this.eduStatus = eduStatus;
        this.eduReason = eduReason;
        this.redirectDatetime = redirectDatetime;
        this.systemMessage = systemMessage;
        this.verifyScore = verifyScore;
        this.verifyStatus = verifyStatus;
        this.verifyId = verifyId;
        this.verifyDatetime = verifyDatetime;
        this.dokuVoidResponseCode = dokuVoidResponseCode;
        this.dokuVoidApprovalCode = dokuVoidApprovalCode;
        this.dokuVoidDatetime = dokuVoidDatetime;
        this.incName = incName;
        this.transactionsDataCardholders = transactionsDataCardholders;
        this.transactionsDataNonAirlineses = transactionsDataNonAirlineses;
        this.transactionsDataAirlineses = transactionsDataAirlineses;
        this.transactionsDataRecur = transactionsDataRecur;
    }

    @Id
    @Column(name = "transactions_id", unique = true, nullable = false)
    public long getTransactionsId() {
        return this.transactionsId;
    }

    public void setTransactionsId(long transactionsId) {
        this.transactionsId = transactionsId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "merchant_payment_channel_id", nullable = true)
    public MerchantPaymentChannel getMerchantPaymentChannel() {
        return this.merchantPaymentChannel;
    }

    public void setMerchantPaymentChannel(MerchantPaymentChannel merchantPaymentChannel) {
        this.merchantPaymentChannel = merchantPaymentChannel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rate_id", nullable = true)
    public Rates getRates() {
        return rates;
    }

    public void setRates(Rates rates) {
        this.rates = rates;
    }

    @Column(name = "inc_mallid", nullable = false)
    public int getIncMallid() {
        return this.incMallid;
    }

    public void setIncMallid(int incMallid) {
        this.incMallid = incMallid;
    }

    @Column(name = "inc_chainmerchant")
    public Integer getIncChainmerchant() {
        return this.incChainmerchant;
    }

    public void setIncChainmerchant(Integer incChainmerchant) {
        this.incChainmerchant = incChainmerchant;
    }

    @Column(name = "inc_amount", nullable = false, precision = 12)
    public BigDecimal getIncAmount() {
        return this.incAmount;
    }

    public void setIncAmount(BigDecimal incAmount) {
        this.incAmount = incAmount;
    }

    @Column(name = "inc_purchaseamount", nullable = false, precision = 12)
    public BigDecimal getIncPurchaseamount() {
        return this.incPurchaseamount;
    }

    public void setIncPurchaseamount(BigDecimal incPurchaseamount) {
        this.incPurchaseamount = incPurchaseamount;
    }

    @Column(name = "inc_transidmerchant", nullable = false, length = 30)
    public String getIncTransidmerchant() {
        return this.incTransidmerchant;
    }

    public void setIncTransidmerchant(String incTransidmerchant) {
        this.incTransidmerchant = incTransidmerchant;
    }

    @Column(name = "inc_words", nullable = false, length = 256)
    public String getIncWords() {
        return this.incWords;
    }

    public void setIncWords(String incWords) {
        this.incWords = incWords;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "inc_requestdatetime", nullable = false, length = 29)
    public Date getIncRequestdatetime() {
        return this.incRequestdatetime;
    }

    public void setIncRequestdatetime(Date incRequestdatetime) {
        this.incRequestdatetime = incRequestdatetime;
    }

    @Column(name = "inc_currency", nullable = false, length = 3)
    public String getIncCurrency() {
        return this.incCurrency;
    }

    public void setIncCurrency(String incCurrency) {
        this.incCurrency = incCurrency;
    }

    @Column(name = "inc_purchasecurrency", nullable = false, length = 3)
    public String getIncPurchasecurrency() {
        return this.incPurchasecurrency;
    }

    public void setIncPurchasecurrency(String incPurchasecurrency) {
        this.incPurchasecurrency = incPurchasecurrency;
    }

    @Column(name = "inc_sessionid", nullable = false, length = 60)
    public String getIncSessionid() {
        return this.incSessionid;
    }

    public void setIncSessionid(String incSessionid) {
        this.incSessionid = incSessionid;
    }

    @Column(name = "inc_email", nullable = false, length = 100)
    public String getIncEmail() {
        return this.incEmail;
    }

    public void setIncEmail(String incEmail) {
        this.incEmail = incEmail;
    }

    @Column(name = "inc_paymentchannel", nullable = false, length = 2)
    public String getIncPaymentchannel() {
        return this.incPaymentchannel;
    }

    public void setIncPaymentchannel(String incPaymentchannel) {
        this.incPaymentchannel = incPaymentchannel;
    }

    @Column(name = "inc_installment_acquirer", length = 5)
    public String getIncInstallmentAcquirer() {
        return this.incInstallmentAcquirer;
    }

    public void setIncInstallmentAcquirer(String incInstallmentAcquirer) {
        this.incInstallmentAcquirer = incInstallmentAcquirer;
    }

    @Column(name = "inc_tenor", length = 5)
    public String getIncTenor() {
        return this.incTenor;
    }

    public void setIncTenor(String incTenor) {
        this.incTenor = incTenor;
    }

    @Column(name = "inc_promoid", length = 5)
    public String getIncPromoid() {
        return this.incPromoid;
    }

    public void setIncPromoid(String incPromoid) {
        this.incPromoid = incPromoid;
    }

    @Column(name = "inc_additional_information", length = 1024)
    public String getIncAdditionalInformation() {
        return this.incAdditionalInformation;
    }

    public void setIncAdditionalInformation(String incAdditionalInformation) {
        this.incAdditionalInformation = incAdditionalInformation;
    }

    @Column(name = "account_id", nullable = false, length = 20)
    public String getAccountId() {
        return this.accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    @Column(name = "system_session", length = 200)
    public String getSystemSession() {
        return this.systemSession;
    }

    public void setSystemSession(String systemSession) {
        this.systemSession = systemSession;
    }

    @Column(name = "transactions_status", length = 1)
    public Character getTransactionsStatus() {
        return this.transactionsStatus;
    }

    public void setTransactionsStatus(Character transactionsStatus) {
        this.transactionsStatus = transactionsStatus;
    }

    @Column(name = "transactions_state", length = 1)
    public Character getTransactionsState() {
        return this.transactionsState;
    }

    public void setTransactionsState(Character transactionsState) {
        this.transactionsState = transactionsState;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "transactions_datetime", length = 29)
    public Date getTransactionsDatetime() {
        return this.transactionsDatetime;
    }

    public void setTransactionsDatetime(Date transactionsDatetime) {
        this.transactionsDatetime = transactionsDatetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "doku_inquiry_invoice_datetime", length = 29)
    public Date getDokuInquiryInvoiceDatetime() {
        return this.dokuInquiryInvoiceDatetime;
    }

    public void setDokuInquiryInvoiceDatetime(Date dokuInquiryInvoiceDatetime) {
        this.dokuInquiryInvoiceDatetime = dokuInquiryInvoiceDatetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "doku_invoke_status_datetime", length = 29)
    public Date getDokuInvokeStatusDatetime() {
        return this.dokuInvokeStatusDatetime;
    }

    public void setDokuInvokeStatusDatetime(Date dokuInvokeStatusDatetime) {
        this.dokuInvokeStatusDatetime = dokuInvokeStatusDatetime;
    }

    @Column(name = "doku_response_code", length = 4)
    public String getDokuResponseCode() {
        return this.dokuResponseCode;
    }

    public void setDokuResponseCode(String dokuResponseCode) {
        this.dokuResponseCode = dokuResponseCode;
    }

    @Column(name = "doku_approval_code", length = 15)
    public String getDokuApprovalCode() {
        return this.dokuApprovalCode;
    }

    public void setDokuApprovalCode(String dokuApprovalCode) {
        this.dokuApprovalCode = dokuApprovalCode;
    }

    @Column(name = "doku_result_message", length = 100)
    public String getDokuResultMessage() {
        return this.dokuResultMessage;
    }

    public void setDokuResultMessage(String dokuResultMessage) {
        this.dokuResultMessage = dokuResultMessage;
    }

    @Column(name = "doku_issuer_bank", length = 100)
    public String getDokuIssuerBank() {
        return this.dokuIssuerBank;
    }

    public void setDokuIssuerBank(String dokuIssuerBank) {
        this.dokuIssuerBank = dokuIssuerBank;
    }

    @Column(name = "doku_result", length = 20)
    public String getDokuResult() {
        return this.dokuResult;
    }

    public void setDokuResult(String dokuResult) {
        this.dokuResult = dokuResult;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "edu_getdata_datetime", length = 29)
    public Date getEduGetdataDatetime() {
        return this.eduGetdataDatetime;
    }

    public void setEduGetdataDatetime(Date eduGetdataDatetime) {
        this.eduGetdataDatetime = eduGetdataDatetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "edu_pass_void_datetime", length = 29)
    public Date getEduPassVoidDatetime() {
        return this.eduPassVoidDatetime;
    }

    public void setEduPassVoidDatetime(Date eduPassVoidDatetime) {
        this.eduPassVoidDatetime = eduPassVoidDatetime;
    }

    @Column(name = "edu_status", length = 1)
    public Character getEduStatus() {
        return this.eduStatus;
    }

    public void setEduStatus(Character eduStatus) {
        this.eduStatus = eduStatus;
    }

    @Column(name = "edu_reason")
    public String getEduReason() {
        return this.eduReason;
    }

    public void setEduReason(String eduReason) {
        this.eduReason = eduReason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "redirect_datetime", length = 29)
    public Date getRedirectDatetime() {
        return this.redirectDatetime;
    }

    public void setRedirectDatetime(Date redirectDatetime) {
        this.redirectDatetime = redirectDatetime;
    }

    @Column(name = "system_message", length = 1024)
    public String getSystemMessage() {
        return this.systemMessage;
    }

    public void setSystemMessage(String systemMessage) {
        this.systemMessage = systemMessage;
    }

    @Column(name = "verify_score")
    public Integer getVerifyScore() {
        return this.verifyScore;
    }

    public void setVerifyScore(Integer verifyScore) {
        this.verifyScore = verifyScore;
    }

    @Column(name = "verify_status", length = 1)
    public Character getVerifyStatus() {
        return this.verifyStatus;
    }

    public void setVerifyStatus(Character verifyStatus) {
        this.verifyStatus = verifyStatus;
    }

    @Column(name = "verify_id", length = 30)
    public String getVerifyId() {
        return this.verifyId;
    }

    public void setVerifyId(String verifyId) {
        this.verifyId = verifyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "verify_datetime", length = 29)
    public Date getVerifyDatetime() {
        return this.verifyDatetime;
    }

    public void setVerifyDatetime(Date verifyDatetime) {
        this.verifyDatetime = verifyDatetime;
    }

    @Column(name = "doku_void_response_code", length = 4)
    public String getDokuVoidResponseCode() {
        return this.dokuVoidResponseCode;
    }

    public void setDokuVoidResponseCode(String dokuVoidResponseCode) {
        this.dokuVoidResponseCode = dokuVoidResponseCode;
    }

    @Column(name = "doku_void_approval_code", length = 15)
    public String getDokuVoidApprovalCode() {
        return this.dokuVoidApprovalCode;
    }

    public void setDokuVoidApprovalCode(String dokuVoidApprovalCode) {
        this.dokuVoidApprovalCode = dokuVoidApprovalCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "doku_void_datetime", length = 29)
    public Date getDokuVoidDatetime() {
        return this.dokuVoidDatetime;
    }

    public void setDokuVoidDatetime(Date dokuVoidDatetime) {
        this.dokuVoidDatetime = dokuVoidDatetime;
    }

    @Column(name = "inc_name", nullable = false, length = 50)
    public String getIncName() {
        return this.incName;
    }

    public void setIncName(String incName) {
        this.incName = incName;
    }

    //@OneToMany(fetch = FetchType.LAZY)
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "transactions")
    public Set<TransactionsDataCardholder> getTransactionsDataCardholders() {
        return this.transactionsDataCardholders;
    }

    public void setTransactionsDataCardholders(Set<TransactionsDataCardholder> transactionsDataCardholders) {
        this.transactionsDataCardholders = transactionsDataCardholders;
    }

    //@OneToMany(fetch = FetchType.LAZY)//, mappedBy = "transactions")
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "transactions")
    public Set<TransactionsDataNonAirlines> getTransactionsDataNonAirlineses() {
        return this.transactionsDataNonAirlineses;
    }

    public void setTransactionsDataNonAirlineses(Set<TransactionsDataNonAirlines> transactionsDataNonAirlineses) {
        this.transactionsDataNonAirlineses = transactionsDataNonAirlineses;
    }

    //@OneToMany(fetch = FetchType.LAZY)
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "transactions")
    public Set<TransactionsDataAirlines> getTransactionsDataAirlineses() {
        return this.transactionsDataAirlineses;
    }

    public void setTransactionsDataAirlineses(Set<TransactionsDataAirlines> transactionsDataAirlineses) {
        this.transactionsDataAirlineses = transactionsDataAirlineses;
    }

    /**
     * @return the dokuHostRefNum
     */
    @Column(name = "doku_host_ref_num", length = 15)
    public String getDokuHostRefNum() {
        return dokuHostRefNum;
    }

    /**
     * @param dokuHostRefNum the dokuHostRefNum to set
     */
    public void setDokuHostRefNum(String dokuHostRefNum) {
        this.dokuHostRefNum = dokuHostRefNum;
    }

    /**
     * @return the reconcileDateTime
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "reconcile_datetime", length = 29)
    public Date getReconcileDateTime() {
        return reconcileDateTime;
    }

    /**
     * @param reconcileDateTime the reconcileDateTime to set
     */
    public void setReconcileDateTime(Date reconcileDateTime) {
        this.reconcileDateTime = reconcileDateTime;
    }

    /**
     * @return the inc3dSecureStatus
     */
    @Column(name = "inc_3dsec_status", length = 50)
    public String getInc3dSecureStatus() {
        return inc3dSecureStatus;
    }

    /**
     * @param inc3dSecureStatus the inc3dSecureStatus to set
     */
    public void setInc3dSecureStatus(String inc3dSecureStatus) {
        this.inc3dSecureStatus = inc3dSecureStatus;
    }

    /**
     * @return the incLiability
     */
    @Column(name = "inc_liability", length = 50)
    public String getIncLiability() {
        return incLiability;
    }

    /**
     * @param incLiability the incLiability to set
     */
    public void setIncLiability(String incLiability) {
        this.incLiability = incLiability;
    }

    @Column(name = "token_id", length = 50)
    public String getTokenId() {
        return tokenId;
    }

    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

//    @Column(name="recur_schedule", length=255)
//    public String getRecurSchedule() {
//        return recurSchedule;
//    }
//
//    public void setRecurSchedule(String recurSchedule) {
//        this.recurSchedule = recurSchedule;
//    }
    //@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "transactions")
    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "transactions")
    public TransactionsDataRecur getTransactionsDataRecur() {
        return this.transactionsDataRecur;
    }

    public void setTransactionsDataRecur(TransactionsDataRecur transactionsDataRecur) {
        this.transactionsDataRecur = transactionsDataRecur;
    }

    @Column(name = "inc_customer_id", length = 50)
    public String getIncCustomerId() {
        return incCustomerId;
    }

    public void setIncCustomerId(String incCustomerId) {
        this.incCustomerId = incCustomerId;
    }

    @Column(name = "device_id", length = 4096)
    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    @Column(name = "converted_amount", precision = 12)
    public BigDecimal getConvertedAmount() {
        return convertedAmount;
    }

    public void setConvertedAmount(BigDecimal convertedAmount) {
        this.convertedAmount = convertedAmount;
    }

    @Column(name = "merchant_notification_response", length = 255)
    public String getMerchantNotificationResponse() {
        return merchantNotificationResponse;
    }

    public void setMerchantNotificationResponse(String merchantNotificationResponse) {
        this.merchantNotificationResponse = merchantNotificationResponse;
    }

    @Column(name = "inc_rewards")
    public Integer getIncRewards() {
        return incRewards;
    }

    public void setIncRewards(Integer incRewards) {
        this.incRewards = incRewards;
    }

    @Column(name = "trx_code_core", length = 120)
    public String getTrxCodeCore() {
        return trxCodeCore;
    }

    public void setTrxCodeCore(String trxCodeCore) {
        this.trxCodeCore = trxCodeCore;
    }

    @Column(name = "oco_id", length = 24)
    public String getOcoId() {
        return ocoId;
    }

    public void setOcoId(String ocoId) {
        this.ocoId = ocoId;
    }

//   @Column(name="batch_id")
//    public Integer getBatchId() {
//        return batchId;
//    }
//
//    public void setBatchId(Integer batchId) {
//        this.batchId = batchId;
//    }
    @Column(name = "partial_amount")
    public Boolean getPartialAmount() {
        return PartialAmount;
    }

    public void setPartialAmount(Boolean PartialAmount) {
        this.PartialAmount = PartialAmount;
    }
    
    @Column(name = "open_amount_status")
    public Boolean getOpenAmount() {
        return OpenAmount;
    }

    public void setOpenAmount(Boolean OpenAmount) {
        this.OpenAmount = OpenAmount;
    }

    @Column(name = "parent_transactions")
    public Long getParentTransactions() {
        return parentTransactions;
    }

    public void setParentTransactions(Long parentTransactions) {
        this.parentTransactions = parentTransactions;
    }

    @Column(name = "transactions_type", length = 1)
    public Character getTransactionsType() {
        return transactionsType;
    }

    public void setTransactionsType(Character transactionsType) {
        this.transactionsType = transactionsType;
    }
}
