package com.onechekoutv1.dto;
// Generated Oct 2, 2012 3:11:56 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TransactionsDataCardholder generated by hbm2java
 */
@Entity
@Table(name="transactions_data_cardholder"
    ,schema="public"
)
public class TransactionsDataCardholder  implements java.io.Serializable {


     private long transactionsId;
     private Transactions transactions;
     private String incCcName;
     private String incAddress;
     private String incCity;
     private String incState;
     private String incCountry;
     private String incZipcode;
     private String incHomephone;
     private String incMobilephone;
     private String incWorkphone;
     private String incBirthdate;

    public TransactionsDataCardholder() {
    }

	
    public TransactionsDataCardholder(long transactionsId, Transactions transactions, String incCcName, String incAddress, String incCity, String incState, String incCountry, String incZipcode, String incHomephone, String incMobilephone) {
        this.transactionsId = transactionsId;
        this.transactions = transactions;
        this.incCcName = incCcName;
        this.incAddress = incAddress;
        this.incCity = incCity;
        this.incState = incState;
        this.incCountry = incCountry;
        this.incZipcode = incZipcode;
        this.incHomephone = incHomephone;
        this.incMobilephone = incMobilephone;
    }
    public TransactionsDataCardholder(long transactionsId, Transactions transactions, String incCcName, String incAddress, String incCity, String incState, String incCountry, String incZipcode, String incHomephone, String incMobilephone, String incWorkphone, String incBirthdate) {
       this.transactionsId = transactionsId;
       this.transactions = transactions;
       this.incCcName = incCcName;
       this.incAddress = incAddress;
       this.incCity = incCity;
       this.incState = incState;
       this.incCountry = incCountry;
       this.incZipcode = incZipcode;
       this.incHomephone = incHomephone;
       this.incMobilephone = incMobilephone;
       this.incWorkphone = incWorkphone;
       this.incBirthdate = incBirthdate;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getTransactionsId() {
        return this.transactionsId;
    }
    
    public void setTransactionsId(long transactionsId) {
        this.transactionsId = transactionsId;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="transactions_id", unique=true, nullable=false)
    public Transactions getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Transactions transactions) {
        this.transactions = transactions;
    }
    
    @Column(name="inc_cc_name", nullable=false, length=50)
    public String getIncCcName() {
        return this.incCcName;
    }
    
    public void setIncCcName(String incCcName) {
        this.incCcName = incCcName;
    }
    
    @Column(name="inc_address", nullable=false, length=1024)
    public String getIncAddress() {
        return this.incAddress;
    }
    
    public void setIncAddress(String incAddress) {
        this.incAddress = incAddress;
    }
    
    @Column(name="inc_city", nullable=false, length=100)
    public String getIncCity() {
        return this.incCity;
    }
    
    public void setIncCity(String incCity) {
        this.incCity = incCity;
    }
    
    @Column(name="inc_state", nullable=false, length=100)
    public String getIncState() {
        return this.incState;
    }
    
    public void setIncState(String incState) {
        this.incState = incState;
    }
    
    @Column(name="inc_country", nullable=false, length=3)
    public String getIncCountry() {
        return this.incCountry;
    }
    
    public void setIncCountry(String incCountry) {
        this.incCountry = incCountry;
    }
    
    @Column(name="inc_zipcode", nullable=false, length=10)
    public String getIncZipcode() {
        return this.incZipcode;
    }
    
    public void setIncZipcode(String incZipcode) {
        this.incZipcode = incZipcode;
    }
    
    @Column(name="inc_homephone", nullable=false, length=15)
    public String getIncHomephone() {
        return this.incHomephone;
    }
    
    public void setIncHomephone(String incHomephone) {
        this.incHomephone = incHomephone;
    }
    
    @Column(name="inc_mobilephone", nullable=false, length=15)
    public String getIncMobilephone() {
        return this.incMobilephone;
    }
    
    public void setIncMobilephone(String incMobilephone) {
        this.incMobilephone = incMobilephone;
    }
    
    @Column(name="inc_workphone", length=15)
    public String getIncWorkphone() {
        return this.incWorkphone;
    }
    
    public void setIncWorkphone(String incWorkphone) {
        this.incWorkphone = incWorkphone;
    }
    
    @Column(name="inc_birthdate", length=14)
    public String getIncBirthdate() {
        return this.incBirthdate;
    }
    
    public void setIncBirthdate(String incBirthdate) {
        this.incBirthdate = incBirthdate;
    }





}


